/**
 * PreviewPost Component
 * 
 * Secure preview page for draft articles generated by n8n automation.
 * Validates previewToken from URL against stored token in Firestore.
 * Shows 403 Forbidden if token is invalid or missing.
 * 
 * Usage: /preview/:id?token=abc123
 */

import React, { useEffect, useState } from 'react';
import { useParams, useSearchParams, useNavigate } from 'react-router-dom';
import { doc, getDoc, updateDoc } from 'firebase/firestore';
import { db } from '../../lib/firebase';
import { ArticleItem } from '../../types';
import {
    ShieldAlert,
    ArrowLeft,
    ExternalLink,
    AlertTriangle,
    Loader2,
    Clock,
    Eye,
    CheckCircle2,
    Bot,
    Send,
    Edit,
    Trash2,
    Check
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useAuthorInfo } from '../../hooks/useAuthorInfo';

type PreviewState = 'loading' | 'authorized' | 'forbidden' | 'not_found' | 'error';

export const PreviewPost: React.FC = () => {
    const { id } = useParams<{ id: string }>();
    const [searchParams] = useSearchParams();
    const navigate = useNavigate();
    const token = searchParams.get('token');

    const [article, setArticle] = useState<ArticleItem | null>(null);
    const [state, setState] = useState<PreviewState>('loading');
    const [errorMessage, setErrorMessage] = useState<string>('');
    const [actionLoading, setActionLoading] = useState<'publish' | 'reject' | null>(null);
    const [actionSuccess, setActionSuccess] = useState<string | null>(null);

    useEffect(() => {
        const fetchArticle = async () => {
            if (!id) {
                setState('not_found');
                setErrorMessage('ID de artículo no proporcionado');
                return;
            }

            try {
                const docRef = doc(db, 'articles', id);
                const docSnap = await getDoc(docRef);

                if (!docSnap.exists()) {
                    setState('not_found');
                    setErrorMessage('Artículo no encontrado');
                    return;
                }

                const data = docSnap.data() as ArticleItem;
                const articleData = { ...data, id: docSnap.id };

                // Security validation for drafts
                if (data.status === 'draft' || data.status === 'rejected') {
                    if (!token) {
                        setState('forbidden');
                        setErrorMessage('Token de acceso requerido');
                        return;
                    }

                    if (data.previewToken !== token) {
                        setState('forbidden');
                        setErrorMessage('Token de acceso inválido');
                        return;
                    }
                }

                setArticle(articleData);
                setState('authorized');

            } catch (err) {
                console.error('Error fetching preview:', err);
                setState('error');
                setErrorMessage('Error al cargar el artículo');
            }
        };

        fetchArticle();
    }, [id, token]);

    // Live author lookup - must be called before any conditional returns (React hooks rules)
    // Uses safe fallbacks when article is not yet loaded
    const { authorName, authorUsername, authorAvatar } = useAuthorInfo(
        article?.authorId,
        article?.author,
        article?.authorAvatar
    );

    // Handle Publish Action
    const handlePublish = async () => {
        if (!id || !token || !article) return;

        setActionLoading('publish');
        try {
            const docRef = doc(db, 'articles', id);
            await updateDoc(docRef, {
                status: 'published',
                publishedAt: new Date().toISOString(),
                previewToken: token // Include token for Firestore rule validation
            });

            setArticle({ ...article, status: 'published' });
            setActionSuccess('¡Artículo publicado exitosamente!');

            // Redirect to published article after 2 seconds
            setTimeout(() => {
                navigate(`/blog/${id}`);
            }, 2000);
        } catch (error) {
            console.error('Error publishing:', error);
            setErrorMessage('Error al publicar. Intenta de nuevo.');
        } finally {
            setActionLoading(null);
        }
    };

    // Handle Reject Action
    const handleReject = async () => {
        if (!id || !token || !article) return;

        setActionLoading('reject');
        try {
            const docRef = doc(db, 'articles', id);
            await updateDoc(docRef, {
                status: 'rejected',
                previewToken: token // Include token for Firestore rule validation
            });

            setArticle({ ...article, status: 'rejected' });
            setActionSuccess('Artículo rechazado.');
        } catch (error) {
            console.error('Error rejecting:', error);
            setErrorMessage('Error al rechazar. Intenta de nuevo.');
        } finally {
            setActionLoading(null);
        }
    };

    // Handle Edit - Redirect to editor
    const handleEdit = () => {
        navigate(`/create/article?edit=${id}`);
    };

    // Loading State
    if (state === 'loading') {
        return (
            <div className="min-h-screen bg-[#0d0d0f] flex items-center justify-center">
                <div className="text-center">
                    <Loader2 className="h-12 w-12 animate-spin text-amber-500 mx-auto mb-4" />
                    <p className="text-slate-400">Cargando preview...</p>
                </div>
            </div>
        );
    }

    // 403 Forbidden State
    if (state === 'forbidden') {
        return (
            <div className="min-h-screen bg-gradient-to-b from-red-950/30 to-[#0d0d0f] flex items-center justify-center p-6">
                <div className="max-w-md w-full text-center">
                    <div className="w-24 h-24 bg-red-500/20 rounded-full flex items-center justify-center mx-auto mb-6 ring-4 ring-red-500/10">
                        <ShieldAlert className="h-12 w-12 text-red-500" />
                    </div>
                    <h1 className="text-4xl font-bold text-red-400 mb-3">403</h1>
                    <h2 className="text-2xl font-bold text-white mb-4">Acceso Denegado</h2>
                    <p className="text-slate-400 mb-8">
                        {errorMessage || 'No tienes permiso para ver este contenido.'}
                    </p>
                    <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl mb-8">
                        <p className="text-sm text-red-300">
                            Este artículo es un <strong>borrador</strong> y requiere un token de acceso válido
                            para ser visualizado.
                        </p>
                    </div>
                    <button
                        onClick={() => navigate('/')}
                        className="inline-flex items-center gap-2 px-6 py-3 bg-white/10 hover:bg-white/15 
                                   text-white font-semibold rounded-xl transition-colors"
                    >
                        <ArrowLeft className="h-4 w-4" />
                        Volver al inicio
                    </button>
                </div>
            </div>
        );
    }

    // 404 Not Found State
    if (state === 'not_found') {
        return (
            <div className="min-h-screen bg-[#0d0d0f] flex items-center justify-center p-6">
                <div className="max-w-md w-full text-center">
                    <div className="w-20 h-20 bg-slate-800 rounded-full flex items-center justify-center mx-auto mb-6">
                        <Eye className="h-10 w-10 text-slate-500" />
                    </div>
                    <h1 className="text-3xl font-bold text-white mb-4">Artículo no encontrado</h1>
                    <p className="text-slate-400 mb-8">{errorMessage}</p>
                    <button
                        onClick={() => navigate('/blog')}
                        className="inline-flex items-center gap-2 px-6 py-3 bg-amber-600 hover:bg-amber-500 
                                   text-white font-semibold rounded-xl transition-colors"
                    >
                        <ArrowLeft className="h-4 w-4" />
                        Ir al Blog
                    </button>
                </div>
            </div>
        );
    }

    // Error State
    if (state === 'error') {
        return (
            <div className="min-h-screen bg-[#0d0d0f] flex items-center justify-center p-6">
                <div className="max-w-md w-full text-center">
                    <div className="w-20 h-20 bg-amber-500/20 rounded-full flex items-center justify-center mx-auto mb-6">
                        <AlertTriangle className="h-10 w-10 text-amber-500" />
                    </div>
                    <h1 className="text-3xl font-bold text-white mb-4">Error</h1>
                    <p className="text-slate-400 mb-8">{errorMessage}</p>
                    <button
                        onClick={() => window.location.reload()}
                        className="inline-flex items-center gap-2 px-6 py-3 bg-amber-600 hover:bg-amber-500 
                                   text-white font-semibold rounded-xl transition-colors"
                    >
                        Reintentar
                    </button>
                </div>
            </div>
        );
    }

    // Authorized - Render Article Preview
    if (!article) return null;

    const isDraft = article.status === 'draft';
    const isRejected = article.status === 'rejected';
    const isAutomated = article.source === 'n8n';

    // Get content text - handle nested structure from n8n
    const getContentText = (): string => {
        if (!article.content) return '';

        // If content is a string, return it directly
        if (typeof article.content === 'string') {
            return article.content;
        }

        // If content has nested parts structure from Gemini
        if (typeof article.content === 'object') {
            const content = article.content as any;
            if (content.parts && Array.isArray(content.parts) && content.parts[0]?.text) {
                return content.parts[0].text;
            }
        }

        return String(article.content);
    };

    const contentText = getContentText();

    return (
        <div className="max-w-[1800px] mx-auto transition-colors animate-fade-in pb-20 bg-[#0d0d0f] min-h-screen">
            {/* Preview Banner - Sticky */}
            <div className={`sticky top-0 z-50 py-3 px-4 text-center font-bold shadow-lg ${isRejected
                ? 'bg-red-600 text-white'
                : isDraft
                    ? 'bg-amber-500 text-black'
                    : 'bg-green-600 text-white'
                }`}>
                <div className="flex items-center justify-center gap-2">
                    <AlertTriangle className="h-4 w-4" />
                    <span>
                        {isRejected
                            ? '🗑️ RECHAZADO - Este artículo fue descartado'
                            : isDraft
                                ? '🔍 MODO PREVIEW - Este artículo es un borrador'
                                : '✅ PUBLICADO - Vista pública'}
                    </span>
                </div>
                {isAutomated && (
                    <p className="text-xs opacity-80 mt-1">
                        Contenido generado automáticamente por n8n
                    </p>
                )}
            </div>

            {/* Top Navigation Bar */}
            <div className="sticky top-12 z-20 bg-[#0d0d0f]/90 backdrop-blur-xl border-b border-white/[0.06] px-6 py-4 flex items-center justify-between">
                <button
                    onClick={() => navigate('/blog')}
                    className="flex items-center gap-2 text-sm font-medium text-slate-400 hover:text-white transition-colors"
                >
                    <ArrowLeft className="h-4 w-4" />
                    Volver al Blog
                </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 px-6 md:px-10 py-10 relative">

                {/* Left Sidebar - Status Info & Actions (Sticky) */}
                <aside className="hidden lg:flex lg:col-span-1 flex-col items-center gap-6 sticky top-36 h-fit">
                    <div className="flex flex-col gap-4 bg-white/5 p-3 rounded-2xl border border-white/10 w-full items-center">
                        {/* Status Indicators */}
                        {isDraft && (
                            <div className="p-3 rounded-xl bg-amber-500/10 text-amber-500 flex flex-col items-center gap-1">
                                <AlertTriangle className="h-5 w-5" />
                                <span className="text-[10px] font-bold uppercase">Borrador</span>
                            </div>
                        )}
                        {isRejected && (
                            <div className="p-3 rounded-xl bg-red-500/10 text-red-500 flex flex-col items-center gap-1">
                                <Trash2 className="h-5 w-5" />
                                <span className="text-[10px] font-bold uppercase">Rechazado</span>
                            </div>
                        )}
                        {isAutomated && (
                            <div className="p-3 rounded-xl bg-blue-500/10 text-blue-400 flex flex-col items-center gap-1">
                                <Bot className="h-5 w-5" />
                                <span className="text-[10px] font-bold uppercase">Auto</span>
                            </div>
                        )}

                        {/* Action Buttons - Only for drafts with valid token */}
                        {isDraft && token && (
                            <>
                                <div className="h-px w-8 bg-white/10 my-1" />

                                {/* Publish Button */}
                                <button
                                    onClick={handlePublish}
                                    disabled={actionLoading !== null}
                                    className={`w-full p-3 rounded-xl bg-green-500/20 text-green-400 hover:bg-green-500/30 
                                               transition-all flex flex-col items-center gap-1 
                                               ${actionLoading === 'publish' ? 'opacity-50 cursor-wait' : 'hover:scale-105'}`}
                                    title="Publicar artículo"
                                >
                                    {actionLoading === 'publish' ? (
                                        <Loader2 className="h-5 w-5 animate-spin" />
                                    ) : (
                                        <Send className="h-5 w-5" />
                                    )}
                                    <span className="text-[10px] font-bold uppercase">Publicar</span>
                                </button>

                                {/* Edit Button */}
                                <button
                                    onClick={handleEdit}
                                    disabled={actionLoading !== null}
                                    className="w-full p-3 rounded-xl bg-blue-500/20 text-blue-400 hover:bg-blue-500/30 
                                               transition-all flex flex-col items-center gap-1 hover:scale-105"
                                    title="Editar artículo"
                                >
                                    <Edit className="h-5 w-5" />
                                    <span className="text-[10px] font-bold uppercase">Editar</span>
                                </button>

                                {/* Reject Button */}
                                <button
                                    onClick={handleReject}
                                    disabled={actionLoading !== null}
                                    className={`w-full p-3 rounded-xl bg-red-500/20 text-red-400 hover:bg-red-500/30 
                                               transition-all flex flex-col items-center gap-1 
                                               ${actionLoading === 'reject' ? 'opacity-50 cursor-wait' : 'hover:scale-105'}`}
                                    title="Rechazar artículo"
                                >
                                    {actionLoading === 'reject' ? (
                                        <Loader2 className="h-5 w-5 animate-spin" />
                                    ) : (
                                        <Trash2 className="h-5 w-5" />
                                    )}
                                    <span className="text-[10px] font-bold uppercase">Rechazar</span>
                                </button>
                            </>
                        )}
                    </div>

                    {/* Success Message */}
                    {actionSuccess && (
                        <div className="p-4 bg-green-500/20 border border-green-500/30 rounded-xl text-center animate-fade-in">
                            <Check className="h-6 w-6 text-green-400 mx-auto mb-2" />
                            <p className="text-xs text-green-300 font-medium">{actionSuccess}</p>
                        </div>
                    )}
                </aside>

                {/* Center Column - Article Content */}
                <article className="lg:col-span-8 lg:px-8">
                    <div className="mb-10 text-center lg:text-left">
                        {article.category && (
                            <>
                                <span className="px-3 py-1 rounded-full bg-amber-500/10 text-amber-400 text-xs font-bold uppercase tracking-wider border border-amber-500/20">
                                    {article.category}
                                </span>
                                <span className="text-slate-500 text-sm mx-2">•</span>
                            </>
                        )}
                        <span className="text-slate-400 text-sm font-medium inline-flex items-center gap-1">
                            <Clock className="h-3.5 w-3.5" />
                            {article.date ? new Date(article.date).toLocaleDateString('es-ES', { day: 'numeric', month: 'long', year: 'numeric' }) : 'Fecha no disponible'}
                        </span>
                        {article.readTime && (
                            <>
                                <span className="text-slate-500 text-sm mx-2">•</span>
                                <span className="text-slate-400 text-sm">{article.readTime} de lectura</span>
                            </>
                        )}
                    </div>

                    <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white leading-tight mb-8 font-display">
                        {article.title || 'Sin título'}
                    </h1>

                    {/* Author Section */}
                    <div className="flex flex-col sm:flex-row items-center justify-center lg:justify-start gap-6 border-y border-white/10 py-6 mb-8">
                        <div className="flex items-center gap-4">
                            <div className="h-12 w-12 rounded-full overflow-hidden ring-2 ring-white/10">
                                <img
                                    src={authorAvatar || 'https://via.placeholder.com/100?text=?'}
                                    alt={authorName || 'Autor'}
                                    className="h-full w-full object-cover"
                                />
                            </div>

                            <div className="flex flex-col">
                                <div className="flex items-center gap-1.5">
                                    <h3 className="font-bold text-lg text-white leading-none">
                                        {authorName || 'Autor desconocido'}
                                    </h3>
                                    <CheckCircle2 className="h-4 w-4 text-amber-500 fill-amber-500/20" />
                                    {isAutomated && (
                                        <span className="ml-2 px-2 py-0.5 rounded-full bg-blue-500/10 text-blue-400 text-[10px] font-bold uppercase">
                                            Bot
                                        </span>
                                    )}
                                </div>
                                <span className="text-xs text-slate-400 font-medium">Contenido de vista previa</span>
                            </div>
                        </div>
                    </div>

                    {/* Cover Image */}
                    <div className="mb-12 rounded-3xl overflow-hidden aspect-video shadow-2xl ring-1 ring-white/10 relative">
                        <img
                            src={article.image || 'https://via.placeholder.com/1200x630?text=Sin+Imagen'}
                            alt={article.title}
                            className="w-full h-full object-cover"
                            onError={(e) => {
                                (e.target as HTMLImageElement).src = 'https://via.placeholder.com/1200x630?text=Sin+Imagen';
                            }}
                        />
                        {isDraft && (
                            <div className="absolute top-4 right-4 px-3 py-1.5 bg-amber-500 text-black text-xs font-bold rounded-full shadow-lg">
                                BORRADOR
                            </div>
                        )}
                    </div>

                    {/* Article Content */}
                    <div className="prose prose-lg prose-invert max-w-none text-slate-300 leading-loose
                                    prose-headings:font-bold prose-headings:text-white
                                    prose-p:text-slate-300 prose-p:leading-relaxed
                                    prose-a:text-amber-400 prose-a:no-underline hover:prose-a:underline
                                    prose-strong:text-white prose-strong:font-semibold
                                    prose-em:text-slate-300
                                    prose-code:bg-black/40 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:text-amber-300 prose-code:text-sm
                                    prose-pre:bg-black/40 prose-pre:rounded-xl prose-pre:border prose-pre:border-white/10
                                    prose-blockquote:border-amber-500 prose-blockquote:bg-amber-500/5 prose-blockquote:rounded-r-xl
                                    prose-ul:text-slate-300 prose-ol:text-slate-300
                                    prose-img:rounded-xl prose-img:ring-1 prose-img:ring-white/10">
                        {contentText ? (
                            contentText.trim().startsWith('<') ? (
                                <div dangerouslySetInnerHTML={{ __html: contentText }} />
                            ) : (
                                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                                    {contentText}
                                </ReactMarkdown>
                            )
                        ) : (
                            <p className="text-slate-500 italic">Sin contenido disponible.</p>
                        )}
                    </div>

                    {/* Tags */}
                    {article.tags && article.tags.length > 0 && (
                        <div className="flex flex-wrap gap-2 mt-12 pt-8 border-t border-white/10">
                            {article.tags.map((tag, idx) => (
                                <span
                                    key={idx}
                                    className="px-4 py-2 rounded-xl bg-white/5 text-slate-400 text-sm font-bold border border-white/5"
                                >
                                    #{tag}
                                </span>
                            ))}
                        </div>
                    )}

                    {/* Original Source Link */}
                    {article.originalLink && (
                        <div className="mt-12 p-6 bg-white/5 rounded-2xl border border-white/10">
                            <h4 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-3">
                                📰 Fuente Original
                            </h4>
                            <a
                                href={article.originalLink}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="inline-flex items-center gap-2 text-amber-400 hover:text-amber-300 hover:underline transition-colors break-all"
                            >
                                {article.originalLink}
                                <ExternalLink className="h-4 w-4 shrink-0" />
                            </a>
                            <p className="text-xs text-slate-500 mt-2">
                                Este contenido fue adaptado/traducido de la fuente original.
                                Todos los derechos pertenecen a sus respectivos autores.
                            </p>
                        </div>
                    )}

                    {/* Back Button */}
                    <div className="mt-12 pt-8 border-t border-white/10">
                        <button
                            onClick={() => navigate(-1)}
                            className="inline-flex items-center gap-2 px-6 py-3 bg-white/10 hover:bg-white/15 
                                       text-white font-semibold rounded-xl transition-colors"
                        >
                            <ArrowLeft className="h-4 w-4" />
                            Volver
                        </button>
                    </div>
                </article>

                {/* Right Sidebar - Preview Info */}
                <aside className="lg:col-span-3 space-y-6">
                    <div className="sticky top-36">
                        <div className="bg-white/[0.02] rounded-2xl border border-white/5 p-6 shadow-xl">
                            <h3 className="text-lg font-bold text-white mb-6 flex items-center gap-2">
                                <div className="h-6 w-1 bg-amber-500 rounded-full"></div>
                                Información del Preview
                            </h3>

                            <div className="space-y-4 text-sm">
                                <div className="flex justify-between">
                                    <span className="text-slate-500">Estado:</span>
                                    <span className={`font-bold ${isDraft ? 'text-amber-400' : isRejected ? 'text-red-400' : 'text-green-400'}`}>
                                        {isDraft ? 'Borrador' : isRejected ? 'Rechazado' : 'Publicado'}
                                    </span>
                                </div>
                                <div className="flex justify-between">
                                    <span className="text-slate-500">Fuente:</span>
                                    <span className="text-slate-300 font-medium">{article.source || 'manual'}</span>
                                </div>
                                <div className="flex justify-between">
                                    <span className="text-slate-500">Categoría:</span>
                                    <span className="text-slate-300 font-medium">{article.category || '-'}</span>
                                </div>
                                <div className="flex justify-between">
                                    <span className="text-slate-500">Dominio:</span>
                                    <span className="text-slate-300 font-medium">{article.domain || '-'}</span>
                                </div>
                            </div>

                            {isDraft && (
                                <div className="mt-6 p-4 bg-amber-500/10 rounded-xl border border-amber-500/20">
                                    <p className="text-xs text-amber-300">
                                        <strong>Nota:</strong> Este artículo está pendiente de revisión.
                                        Solo es visible con el token de preview.
                                    </p>
                                </div>
                            )}
                        </div>
                    </div>
                </aside>
            </div>
        </div>
    );
};

export default PreviewPost;
